### ISSUE TITLE
Occasional audio stutter issue during a scene switch

### ISSUE THREAD

**Issue by matijaerceg** [matijaerceg/DandiDoesIt#14]
Sometimes, after changing a scene, the audio being sent to Twitch seems to stutter until OBS is re-started.

**Comment by matijaerceg** [comment]
Matching all sample rates of audio devices to 48khz, to see if that helps. Hard to reproduce, so it's a wait-and-see situation. Open to any input/help here..

**Comment by plachenko** [comment]
Might be a last resort option but have you thought about using a [multi PC stream setup through NDI](https://obsproject.com/forum/resources/obs-ndi-newtek-ndi%E2%84%A2-integration-into-obs-studio.528/)? You can also look into ffmpeg over UDP if you don't want to deal with plugins. The main PC could handle the audio while the second PC handles any scene switching.

**Comment by matijaerceg** [comment]
Yeah, a multi PC setup is probably unavoidable as we add complexity. However, a lot of the audio is built into scene switching, as we use a lot of effects/alerts. I'm not looking forward to crossing that bridge! lol

Anyway, no problem yesterday since syncing up the sample rates; fingers crossed.

**Comment by matijaerceg** [comment]
haven't had an issue since adjusting sample rate, gonna close it and keep an eye on it :D
